### ISSUE TITLE
'Unreachable' error when uploading llm "end" events to the hosted version

### ISSUE THREAD

**Issue by Valian** [lunary-ai/lunary#677]
Hi! I'm creating an issue because I'm not sure how I could reach you otherwise. 

Since three days we can't get lunary.ai ingest "llm" "end" events 😢 When looking into logs, error reason is "unreachable". Other event types are coming through. We didn't deploy any changes to production since these 3 days, so something must have happened on your side... 

I went through the API endpoint for ingesting new events and I don't see a place where error could be "unreachable". I wrote a message on an in-app chat with more details.

<img width="354" alt="image" src="https://github.com/user-attachments/assets/a2f791f7-2dfc-4abd-97c4-f64a9f31d87f" />

Thank you in advance!

**Comment by hughcrt** [comment]
Hi, sorry about that. I've answered to your colleague on Crisp:
It seems there's a problem from the package we use for tokenization (tiktoken) when the token usage is not reported in the events (which is your case). When the process is running for too long, there's a WASM error. I will open an issue on their repo, but in the meantime I've modified the ingestion code so that it'll still ingest the output. But for now everything seems to work. We will closely monitor this
