### ISSUE TITLE
Lunary LLM call outputs not visible.

### ISSUE THREAD

**Issue by anirudh-32** [lunary-ai/lunary#678]
We haven't deployed any new code changes to our dev, prod environments. All LLM calls are showing up in traces and in logs, but the logs are greyed out (as opposed to green when working fine). We use integration of lunary with LCEL.

Upon investigating the parent trace of the greyed out log, we can see that that the model row has a cross on it.

Other details: timing information, costing information and token count is not available in the logs section.

![Screenshot 2024-12-23 at 1 18 24 PM](https://github.com/user-attachments/assets/80150211-249c-4961-8f2a-561b9561a162)
![Screenshot 2024-12-23 at 2 47 27 PM](https://github.com/user-attachments/assets/7d852f9c-953d-4b7d-9aae-8041eb0c411b)

**Comment by hughcrt** [comment]
Hi, it seems there's a problem from the package we use for tokenization (tiktoken) when the token usage is not reported in the events (which is your case). When the process is running for too long, there's a WASM error. I will open an issue on their repo, but in the meantime I've modified the ingestion code so that it'll still ingest the output. But for now everything seems to work. We will closely monitor this
